= Components of a {core-connector} template

This section gives an overview of the components of https://github.com/modusintegration/mojaloop-cbs-adapter-template[the generic {core-connector} template]. The CBS-vendor-specific templates are not discussed here but they have a similar setup of components so the below information can act as guidance to those too.

When you start developing a template, check if the CBS vendor already has a template in https://github.com/modusintegration[the *modusintegration* GitHub repository] (search on the name of the vendor). When no vendor-specific template exists yet, use the generic {core-connector} template. When working with a CBS vendor who already has an existing template in place, use the existing template as the basis.

== `client-adapter-interface` folder

Inside `src/main/resources/`, there is a file called `api.yaml`. This file contains the definition of the {product-name} API.

NOTE: At the time of writing, the `api.yaml` Swagger file of https://github.com/modusintegration/mojaloop-cbs-adapter-template[the generic {core-connector} template] is not up-to-date.

*Question: Anything else in `src/main/resources/` that we need to talk about?*

The `client-adapter-interface` folder also contains a `pom.xml` configuration file to specify the dependencies and plugins that the `client-adapter-interface` component relies on.

*Question: Any entries in `pom.xml` that deserve special attention?*

== `client-adapter` folder

Contains the implementations of the {product-name} API endpoints, as well as the routers, processors, and beans required to translate and route messages from one endpoint to another (in our case, from DFSP backend endpoints to {product-name} API endpoints, and the other way around).

It comes with:

* A `lib` folder that contains a Camel DataSonnet `.jar` file. *Question: What is the role of this file?*
* A `src/main` folder with all of the source material for building the {core-connector} project:
** `java/com/modus/client/exception/`: Exception handling resources. *Question: Anything that deserves special attention?*
** `java/com/modus/client/jaxrs/`: The classes that implement the {product-name} API endpoint interfaces.
** `java/com/modus/client/router/`: The router that defines the rules for moving messages between endpoints.
** `java/com/modus/client/Application.java`: *Question: What is the role of this file?*
** `resources/mappings/`: The DataSonnet mappings between the {product-name} API and the DFSP backend API (referenced by the router). 
** `resources/spring/application.xml`: *Question: What is the role of this file?*
** `resources/spring/cxf.xml`: *Question: What is the role of this file?*
** `resources/spring/mappings.xml`: *Question: What is the role of this file?*
** `resources/application.xml`: A properties file with values that can be used during testing.
** `resources/log4j.xml`: A configuration file for the Log4j logging utility.
* A `src/test/java/com/modus/client/` folder with tests for the DataSonnet mappings.
* A `Dockerfile` file: *Question: Is this needed? What is it for?*
* A `pom.xml` configuration file to specify the dependencies and plugins that the `client-adapter` component relies on.

== `client-adapter-db` folder

Contains the routers, processors, and beans required to translate and route messages from the DFSP backend to {core-connector} (and the other way around) when the DFSP's backend uses database-based procedural calls (as opposed to API calls) for integrating with external systems.

== `client-adapter-it` folder

Contains integration tests. *Question: Anything that deserves special attention?*

It comes with:

* An `src/test` folder, which contains the integration tests and the configuration of the Log4j logging utility.
* A `pom.xml` configuration file to specify the dependencies and plugins that the `client-adapter-it` component relies on. 

== `client-adapter-rest-mock` folder

Contains the implementation of a mock CBS backend and REST API, which can be used for testing purposes.
*Question: Is this OK?*

== `client-adapter-soap-mock` folder

Contains the implementation of a mock CBS backend and SOAP API, which can be used for testing purposes.
*Question: Is this OK?*

== `.gitlab-ci.yml` file

Contains the CI/CD configuration for building and testing {core-connector}.
*Question: Is this OK?*

== `Dockerfile` file

The Dockerfile for building the {core-connector} image.

== `dependency_tree.txt` file

*Question: What is the role of this file?*

== `pom.xml` configuration file

Contains the Project Object Model (POM) for the project. The POM is the basic unit of work in Maven. It is an XML file that contains information about the project and configuration details (such as modules, dependencies, plugins) used by Maven to build the project. For more information on how `pom.xml` is structured, see https://maven.apache.org/guides/introduction/introduction-to-the-pom.html[Maven documentation].

== `run.sh` file

A script to run {core-connector}.
*Question: Is this OK?*