build_dir: ./build/pdf
publish: true
clean: true
command: bundle exec asciidoctor-pdf -r ./optimizer-hexapdf.rb
plimit: 5
insert_start_page: false
section_merge_strategy: enclose
asciidoc:
  attributes:
    chapter-signifier: ''
    icons: font
    optimize: ''
    pdf-theme: pdf-theme.yml
    pdf-fontsdir: ./
    # setting pdf-version to 1.3 allows non-ASCII characters to be used in title field of PDF info
    pdf-version: '1.3'
    #sectnums: ''
    source-highighter: rouge
    toc: ''
    toclevels: 4
    xrefstyle: short
