@startuml

autonumber
skinparam activityFontSize 4
skinparam activityDiamondFontSize 30
skinparam activityArrowFontSize 24
skinparam defaultFontSize 24
skinparam noteFontSize 24
skinparam monochrome true

participant "DFSP Core Backend" as backend

box Payment Manager
participant "Core Connector" as cc
participant "Mojaloop Connector" as sob
end box

participant "Mojaloop Switch" as sw


== send money ==

    backend -> cc: POST /sendmoney (sync)
    cc -> sob: POST /transfers (sync)
    sob -> sw: GET /parties/{type}/{id}
    sw -> sob: PUT /parties/{type}/{id}
    sob -> cc: Response to POST /transfers \n (contains party info + transferId) \n HTTP 200 result (sync)
    cc -> backend: Response to POST /sendmoney \n (contains party info + transferId) \n HTTP 200 result (sync) 
    backend -> cc: PUT /sendmoney/{transferId} (sync) \n ("acceptParty": true)
    cc -> sob: PUT /transfers/{transferId} (sync) \n ("acceptParty": true)
    sob -> sw: POST /quotes
    sw -> sob: PUT /quotes/{id}
    sob -> sob: Check quote rules
    sob -> cc: Response to PUT /transfers/{transferId} \n (contains quote) \n HTTP 200 result (sync)
    cc -> backend: Response PUT /sendmoney/{transferId} \n (contains quote) \n HTTP 200 result (sync)
    backend -> cc: PUT /sendmoney/{transferId} (sync) \n ("acceptQuote": true)
    cc -> sob: PUT /transfers/{transferId} (sync) \n ("acceptQuote": true)
    sob -> sw: POST /transfers
    sw -> sw: Perform (NDC) liquidity check
    sw -> sw: Reserve funds
    sw -> sw: Perform validation
    sw -> sw: Commit funds
    sw -> sob: PUT /transfers/{id} \n transferState=COMMITTED
    sob -> cc: Response to PUT /transfers/{transferId} \n Transfer successful \n HTTP 200 result (sync)
    cc -> backend: Response PUT /sendmoney/{transferId} \n Transfer successful \n HTTP 200 result (sync)

@enduml