= User authentication with OpenID Connect

{product-name} and Keycloak implement the OpenID Connect protocol. The following sequence flow describes the OpenID Connect user authentication process utilised by {product-name}.

. When the user accesses {product-name} and the browser loads, the browser makes a request to the Experience API to obtain user information.
. The Experience API checks if the user has a session cookie with a valid token.
.. If there is a valid token, the Experience API calls Keycloak to get the user information, and the browser page renders normally, presenting {product-name} to the user.
.. If there is no token or the token has expired, then the Experience API sends a redirect to a Keycloak sign-in page in its response to the browser.
. On the Keycloak sign-in page, the user enters their credentials to log in to {product-name}.
. Keycloak verifies the user's credentials. When it succeeds, Keycloak redirects the browser back to the Experience API service and passes an Authorization Code in its response.
. The Experience API presents the Authorization Code to Keycloak to verify if Keycloak has indeed just authenticated that user and to request tokens.
. If the Authorization Code matches the code that Keycloak gave to the browser, then Keycloak gives the Experience API back an ID Token and an Access Token. +
 +
All access tokens are stored and cached by the Experience API. Access tokens have an expiry time and on every request, the Experience API checks to see if the access token has expired. If the token has expired, the Experience API does a handshake with Keycloak to refresh the token. +
 +
(In *Keycloak > Realm Settings* (left-hand side navigation pane) *> Token tab* (right-hand side pane), you can set up how you want the refresh to happen, how long the session can be live or idle, and so on.)
. The Experience API can use the ID Token to send a request for user information to Keycloak, and Keycloak will return a set of what is called Claims (data about the user such as username).
. The Experience API looks up from the session the roles that the user has and it will decide based on that what action to allow to the user.

For further details on the OpenID Connect authentication flow (Authorization Code flow), see https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[OpenID Connect Core documentation]. Note that in OpenID Connect terminology, "Client" is the application that requests the authentication of a user, which in the above flow is the {product-name} Experience API.