= Overview of technologies and resources

== Technologies

{core-connector} templates are built in Java in https://www.tutorialspoint.com/apache_camel/apache_camel_tutorial.pdf[Apache Camel]. Apache Camel provides a rule-based routing and mediation engine, which allows for message translation and message routing between the DFSP Core Backend and the Mojaloop Switch.

Templates are Spring-based applications built with Spring Boot. https://spring.io/projects/spring-boot[Spring Boot] is a module of the Spring Framework, which makes it easier to configure Java Spring applications or RESTful services.

Another framework, https://cxf.apache.org/[Apache CXF], is used for SOAP web services support and other configurations. *Question: In the case of a REST-based implementation, what is CXF used for?*

https://maven.apache.org/[Maven] is used to build and manage Camel projects.

https://datasonnet.s3-us-west-2.amazonaws.com/docs-ci/primary/master/datasonnet/1.0-SNAPSHOT/index.html[DataSonnet], an open source data transformation language, takes care of the JSON-to-JSON mappings between the {product-name} API and the DFSP Core Backend API.

Familiarity with the above technologies is a prerequisite to handling templates.

== Resources

To help implementation efforts, DFSPs are provided with:

*Question: Should the Swagger + REST template be placed in the available in pm4ml repo?*

* https://github.com/modusintegration/mojaloop-payment-manager-specification/blob/main/mojaloop_payment_manager_API.yaml[The Swagger specification of the {product-name} API]. The {product-name} API is the API that the DFSP Core Backend talks to, leveraging {core-connector}.
* https://github.com/modusintegration/pm4ml-core-connector-rest-template[A generic {core-connector} template for REST-based DFSP Core Backend implementations].
////
* A {core-connector} template per CBS provider https://github.com/modusintegration[in the *modusintegration* GitHub repository]. You can search for a template based on its name. Templates use the following naming convention: `<CBS vendor name>-mojaloop-adapter` or `<CBS vendor name>-client-adapter` +
 +
Note that in the future, the word `adapter` will no longer be used. Existing repositories will not be renamed but moving forward, new repositories will be using the term `core-connector`.
* https://github.com/modusintegration/cbs-core-connectors-helm-repo[The Helm chart (per template) that deploys {core-connector}].
* https://github.com/modusintegration/mojaloop-simulator-core-connector[Mojaloop Simulator Core Connector] and https://github.com/modusintegration/mojaloop-payment-manager-helm/tree/master/mojaloop-simulator-core-connector[its Helm chart]. The Mojaloop Simulator {core-connector} is part of the simulator DFSP setup, employed when conducting initial tests with newly onboarded DFSPs.
////

*Question: Should there be a Helm chart that deploys the REST-based CC?*