= Integration as a Payee DFSP

The following diagram illustrates how a Payee DFSP interacts with {product-name} and the Mojaloop Switch at the level of API calls.

NOTE: The simplified API between {product-name} and the DFSP backend is a synchronous HTTP API, while the interface between {product-name} and the Mojaloop Switch is the https://docs.mojaloop.io/mojaloop-specification/#api-definition[asynchronous Mojaloop FSPIOP API]. +
 +
Specification of the simplified inbound API (Mojaloop Switch → Payment Manager → Payee DFSP) is provided in the form of a Swagger `.yaml` file (`payment_manager_inbound_API.yaml`).

.Payee DFSP transfer flow
image::PM4ML_transfer_flow_payee.svg[width=80%, height=80%]

== Example `GET /parties/{idType}/{idValue}` request

The following example shows a `GET /parties/{idType}/{idValue}` request:

[source,json]
----
GET /parties/MSISDN/123456789 HTTP/1.1
Content-Type: application/json
----

== Example success response to `GET /parties/{idType}/{idValue}`

The following example shows a response to a `GET /parties/{idType}/{idValue}` request when the request is successful.

[source,json]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "type": "CONSUMER",
  "idType": "MSISDN",
  "idValue": "123456789",
  "displayName": "Antoine Dujardin",
  "firstName": "Antoine",
  "middleName": "Paul",
  "lastName": "Dujardin",
  "dateOfBirth": "1977-07-17"
}
----

== Example error response to `GET /parties/{idType}/{idValue}`

The following example shows a response to a `GET /parties/{idType}/{idValue}` request when the request fails.

////
 due to the Payee party not being found
//// 

////
*statusCode + message??? 3204: Party not found???*
////

[source,json]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "statusCode": "string",
  "message": "string"
}
----

== Example `POST /quoterequests` request

The following example shows a `POST /quoterequests` request:

[source,json]
----
POST /quoterequests
Content-Type: application/json
Accept: application/json

{
  "quoteId": "7c23e80c-d078-4077-8263-2c047876fcf6",
  "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
  "to": {
    "type": "CONSUMER",
    "idType": "MSISDN",
    "idValue": "987654321", 
    "displayName": "Aamir Fakhir",
    "firstName": "Aamir",
    "middleName": "Abdel",
    "lastName": "Fakhir",
    "dateOfBirth": "1966-06-16"
  },
  "from": {
    "type": "CONSUMER",
    "idType": "MSISDN",
    "idValue": "123456789",
    "displayName": "Antoine Dujardin",
    "firstName": "Antoine",
    "middleName": "Paul",
    "lastName": "Dujardin",
    "dateOfBirth": "1977-07-17"
  },
  "amountType": "SEND",
  "amount": "50",
  "currency": "EUR",
  "feesAmount": "0",
  "feesCurrency": "EUR",
  "transactionType": "TRANSFER",
  "initiator": "PAYER",
  "initiatorType": "CONSUMER",
  "geoCode": {
    "latitude": "43.6047",
    "longitude": "1.4442"
  },
  "note": "from Antoine",
  "expiration": "2019-11-15T22:17:28.985-01:00"
}
----

== Example success response to `POST /quoterequests`

The following example shows a response to a `POST /quoterequests` request when the request is successful.

[source,json]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "quoteId": "7c23e80c-d078-4077-8263-2c047876fcf6",
  "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
  "transferAmount": "50",
  "transferAmountCurrency": "EUR",
  "payeeReceiveAmount": "50",
  "payeeReceiveAmountCurrency": "EUR",
  "payeeFspFeeAmount": "0",
  "payeeFspFeeAmountCurrency": "EUR",
  "payeeFspCommissionAmount": "0",
  "payeeFspCommissionAmountCurrency": "EUR",
  "expiration": "2019-11-15T22:17:28.985-01:00",
  "geoCode": {
    "latitude": "43.6047",
    "longitude": "1.4442"
  }
}
----

== Example error response to `POST /quoterequests`

The following example shows a response to a `POST /quoterequests` request when the request fails.

////
 due to the `quoteId` not being found
////

////
*statusCode + message???* *3205: Quote ID not found???*
////

[source,json]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "statusCode": "string",
  "message": "string"
}
----

== Example `POST /transfers` request

The following example shows a `POST /transfers` request:

[source,json]
----
POST /transfers
Content-Type: application/json
Accept: application/json

{
  "transferId": "85feac2f-39b2-491b-817e-4a03203d4f14",
  "quote": {
    "quoteId": "7c23e80c-d078-4077-8263-2c047876fcf6",
    "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
    "transferAmount": "50",
    "transferAmountCurrency": "EUR",
    "payeeReceiveAmount": "50",
    "payeeReceiveAmountCurrency": "EUR",
    "payeeFspFeeAmount": "0",
    "payeeFspFeeAmountCurrency": "EUR",
    "payeeFspCommissionAmount": "0",
    "payeeFspCommissionAmountCurrency": "EUR",
    "expiration": "2019-11-15T22:17:28.985-01:00",
    "geoCode": {
      "latitude": "43.6047",
      "longitude": "1.4442"
    }
  },
  "from": {
    "type": "CONSUMER",
    "idType": "MSISDN",
    "idValue": "123456789",
    "displayName": "Antoine Dujardin",
    "firstName": "Antoine",
    "middleName": "Paul",
    "lastName": "Dujardin",
    "dateOfBirth": "1977-07-17"
  },
  "to": {
    "type": "CONSUMER",
    "idType": "MSISDN",
    "idValue": "987654321",
    "displayName": "Aamir Fakhir",
    "firstName": "Aamir",
    "middleName": "Abdel",
    "lastName": "Fakhir",
    "dateOfBirth": "1966-06-16"
  },
  "amountType": "SEND",
  "currency": "EUR",
  "amount": "50",
  "transactionType": "TRANSFER",
  "note": "from Antoine"
}
----

== Example success response to `POST /transfers`

The following example shows a response to a `POST /transfers` request when the request is successful.

[source,json]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "homeTransactionId": "53979be2-3bfe-45aa-ade7-92ea4ce4e74e"
}
----

== Example error response to `POST /transfers`

The following example shows a response to a `POST /transfers` request when the request fails.

////
 due to the `transferId` not being found
//// 

////
*statusCode + message??? 3208: Transfer ID not found*
////

[source,json]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "statusCode": "string",
  "message": "string"
}
----
