= Setting up the {sdk} Scheme Adapter with a mock DFSP backend

This section provides quick start guidance to setting up the {sdk} Scheme Adapter locally with a mock DFSP backend. This configuration is suitable as a starting point for DFSPs wishing to utilise the {sdk} Scheme Adapter for integrating their backend systems with a {hub}-API-enabled Hub.

NOTE: The instructions provided here are for Linux-based systems. For Mac and/or Windows, you will need to translate the following for your environment.

*Prerequisites:*

Make sure you have docker and docker-compose installed locally. For detailed instructions, see the https://docs.docker.com/v17.12/install/[Install Docker] and https://docs.docker.com/compose/install/[Install Docker Compose] documentation by Docker, respectively.

*Steps:*

. Clone the Mock DFSP Backend repository locally:
.. Change directory into your workspace, then to clone using HTTPS:
+
[source,syntaxhighlighter-pre]
----
$ git clone https://github.com/modusbox/mojaloop-sdk-mock-dfsp-backend.git
----
+
Or clone using SSH:
+
[source,syntaxhighlighter-pre]
----
$ git clone git@github.com:modusbox/mojaloop-sdk-mock-dfsp-backend.git
----
.. Now change directory into the cloned repository directory:
+
[source,syntaxhighlighter-pre]
----
$ cd mojaloop-sdk-mock-dfsp-backend
----
. Edit the Scheme Adapter configuration to point the Scheme Adapter at your {hub}-API-enabled Hub or simulator:
.. Use your favourite text editor to edit the file `src/scheme-adapter.env`. Change the value of the `PEER_ENDPOINT` variable to the DNS name or IP address and port number of your {hub}-API-enabled Hub or simulator.
.. Save the file.
. Use docker-compose to download and run the pre-built Scheme Adapter, shared cache (redis) and mock DFSP backend containers locally. Change directory into the `src` subfolder and run docker-compose:
+
[source,syntaxhighlighter-pre]
----
$ cd src/
$ docker-compose up
----
+
You should see docker download the pre-built docker images for the Scheme Adapter, shared cache (redis), and mock DFSP backend. Docker-compose will start the containers.
. Test the outbound (sending money) API:
.. Find the IP address of the mock DFSP backend container. To do this, find the list of docker networks on your local machine:
+
[source,syntaxhighlighter-pre]
----
$ docker network ls
----
.. Identify the docker network created by docker-compose. Docker-compose will assign a name based on the directory name from which you ran the `docker-compose up` command.
.. Once you have identified the network, you can use:
+
[source,syntaxhighlighter-pre]
----
$ docker network inspect {network name}
----
+
This will print a JSON structure to the terminal containing the set of containers in the network and their individual IP addresses.
.. Use the following command to tell the mock DFSP backend to initiate an outbound money transfer via the Scheme Adapter: +
 +
*NOTE:* Do not forget to substitute in the correct IP address for the mock DFSP backend container.
+
[source,syntaxhighlighter-pre]
----
curl -X POST \
  http://{MOCK DFSP Backend Container IP Address}:3000/send \
  -H 'Content-Type: application/json' \
  -d '{
    "from": {
        "displayName": "John Doe",
        "idType": "MSISDN",
        "idValue": "123456789"
    },
    "to": {
        "idType": "MSISDN",
        "idValue": "987654321"
    },
    "amountType": "SEND",
    "currency": "USD",
    "amount": "100",
    "transactionType": "TRANSFER",
    "note": "test payment",
    "homeTransactionId": "123ABC",
    "quoteRequestExtensions": [
        {
            "key": "KYCNationality",
            "value": "US"
        }
    ]
}'
----
+
The `POST /send` call forwards to `POST /transfers` in the {sdk} Scheme Adapter. The response from the above call should indicate the result of the communication between the {sdk} Scheme Adapter and the {hub}-API-enabled Hub or simulator.
. Speak to your Hub Operator or use your simulator to test the inbound (receiving money) API.
. You can now examine the code of the mock DFSP backend to understand how it implements the {sdk} Scheme Adapter simplified inbound API.