@startuml

autonumber
skinparam activityFontSize 4
skinparam activityDiamondFontSize 30
skinparam activityArrowFontSize 24
skinparam defaultFontSize 24
skinparam noteFontSize 24
skinparam monochrome true

actor "DFSP User" as user
participant "Payment Manager \n accessed via browser" as browser
participant "Experience API" as api
participant "Keycloak" as keycloak

user -> browser: Access Payment Manager
browser -> api: Request user information
api -> api: Check if user already has a session \n with a valid access token
alt Access token is valid
api -> keycloak: Request user information (using ID token)
keycloak -> api: Return user information
api -> browser: Return user information
browser -> user: Display Payment Manager homepage
else No access token or access token is not valid
api -> browser: Redirect request to sign-in page
browser -> user: Display sign-in page
user -> browser: Sign in to Payment Manager
browser -> api: Send authentication request
api -> keycloak: Send authentication request
keycloak -> keycloak: Verify user's credentials
keycloak -> api: Pass authorization code
api -> keycloak: Present authorization code to request tokens
keycloak -> api: Provide ID token and access token
api -> keycloak: Request user information (using ID token)
keycloak -> api: Return user information
api -> browser: Return user information
browser -> user: Display Payment Manager homepage
end
user -> browser: Interact with Payment Manager
browser -> api: Send user's action request 
api -> api: Look up user's roles and permissions \n and allow/deny user action
api -> browser: Allow/deny user action
browser -> user: Display requested page or \n message about missing permission

@enduml