= Process overview

To provide context to the processes that {connection-wizard} facilitates, this section...

== Certificates
=== TLS server certificates

Every time a DFSP makes an API call to the Hub, the Hub is requested to present its server certificate. The Hub must send its server certificate chain to the DFSP whenever requested. The DFSP then validates the Hub's server certificate against the certificate shared earlier.

Likewise, when the Hub makes an API call to a DFSP, the DFSP must present its server certificate, which the Hub will validate against the DFSP server certificate shared earlier and stored locally at the Hub.

Before connecting to the Hub, the DFSP and Hub must exchange their server certificate chains for installing in their respective outbound gateways.


=== TLS client certificates
Exchanging CSRs
The Mowali Hub and the DFSP exchange Certificate Signing Requests (CSRs) to request that the other party's CA sign their X.509 client certificate. As part of this process, the Hub Operator completes the folowing steps:

. Request CSR from DFSP.
. Sign DFSP's client certificate.
. Send signed DFSP client certificate and the Mowali CA's root certificate to DFSP for installation.
. Generate Hub client certificate and send CSR to DFSP for signing
. Import and install the Hub client certificate signed by the DFSP's CA, as well as the root certificate of the DFSP's CA.
. Send the Mowali CA certificate to the DFSP. 

The DFSP's signed client certificate will be supplied as part of the TLSv1.2 handshake certificate exchange when the DFSP is making API calls to the Hub. 

The Hub must supply a client certificate signed by the DFSP's CA as part of the TLSv1.2 handshake certificate exchange when making API callbacks to the DFSP. Generate a client certificate and CSR to send to the DFSP for signing.

=== JWS certificates
All DFSPs and the Mowali Hub itself must have a JWS certificate, which they then share among themselves. DFSPs create their own JWS certificates and then upload for distribution to other DFSPs. 