@startuml
autonumber
skinparam activityFontSize 4
skinparam activityDiamondFontSize 30
skinparam activityArrowFontSize 24
skinparam defaultFontSize 24
skinparam noteFontSize 24
skinparam monochrome true

participant "Mojaloop Switch" as sw

participant "Payment Manager" as sib
  
participant "DFSP Core Backend" as backend


== receive money ==

    sw -> sib: GET /parties/{type}/{id}
    sib -> backend: GET /parties/{idType}/{idValue} (sync)
    alt Payee not found
    backend -> sib: Return error \n HTTP 200 result (sync)
    sib -> sw: PUT /parties/{type}/{id}/error
    else Payee found
    backend -> sib: Return Payee info \n HTTP 200 result (sync)
    sib -> sw: PUT /parties/{type}/{id}
    end
    sw -> sib: POST /quotes
    sib -> backend: POST /quoterequests (sync)
    alt Quote request fails
    backend -> sib: Return error \n HTTP 200 result (sync)
    sib -> sw: PUT /quotes/{id}/error
    else Quote request is successful
    backend -> sib: Return quote \n HTTP 200 result (sync)
    sib -> sw: PUT /quotes/{id}
    end
    sw -> sw: Perform liquidity check
    sw -> sw: Reserve funds
    sw -> sib: POST /transfers
    sib -> backend: Process transfer \n POST /transfers (sync)
    backend -> backend: Perform internal checks
    alt Transfer fails Payee DFSP internal check
    backend -> backend: Cancel reserved funds
    backend -> sib: Return error \n HTTP 200 result (sync)
    sib -> sw: PUT /transfers/{id}/error
    else Transfer fails validation by Switch
    backend -> backend: Reserve funds
    backend -> sib: Transfer successful \n HTTP 200 result (sync)
    sib -> sw: PUT /transfers/{id} \n transferState=RESERVED
    sw -> sw: Perform validation
    sw -> sw: Cancel reserved funds
    sw -> sib: PATCH /transfers/{id} \n transferState=ABORTED
    sib -> backend: PUT /transfers/{transferId} \n transferState=ABORTED
    backend -> backend: Cancel reserved funds
    else Transfer is successful
    backend -> backend: Reserve funds
    backend -> sib: Transfer successful \n HTTP 200 result (sync)
    sib -> sw: PUT /transfers/{id} \n transferState=RESERVED
    sw -> sw: Perform validation
    sw -> sw: Commit funds
    sw -> sib: PATCH /transfers/{id} \n transferState=COMMITTED
    sib -> backend: PUT /transfers/{transferId} \n transferState=COMMITTED
    backend -> backend: Move funds to Payee's account \n managed internally in Payee DFSP
    end

@enduml