@startuml

autonumber
skinparam activityFontSize 4
skinparam activityDiamondFontSize 30
skinparam activityArrowFontSize 24
skinparam defaultFontSize 24
skinparam noteFontSize 24
skinparam monochrome true

participant "DFSP Core Backend" as backend

participant "Payment Manager" as sob

participant "Mojaloop Switch" as sw


== send money ==

    backend -> sob: POST /sendmoney (sync)
    alt Payee not found
    sob -> sw: GET /parties/{type}/{id}
    sw -> sob: PUT /parties/{type}/{id}/error
    sob -> backend: Return error (sync)    
    else Payee DFSP and Payee found
    sob -> sw: GET /parties/{type}/{id}
    sw -> sob: PUT /parties/{type}/{id}
    sob -> backend: Return party info \n HTTP 200 result (sync) 
    end   
    backend -> sob: PUT /sendmoney/{transferId} (sync) \n ("acceptParty": true) 
    sob -> sw: POST /quotes
    alt Quote request fails
    sw -> sob: PUT /quotes/{id}/error
    sob -> backend: Return error (sync)
    else Quote request is successful
    sw -> sob: PUT /quotes/{id}
    sob -> sob: check quote rules
    sob -> backend: Return quote \n HTTP 200 result (sync)
    end
    backend -> sob: PUT /sendmoney/{transferId} (sync) \n ("acceptQuote": true)
    sob -> sw: POST /transfers
    sw -> sw: Perform (NDC) liquidity check
    alt Transfer execution would exceed NDC
    sw -> sob: PUT /transfers/{id}/error
    sob -> backend: Return error (sync)
    else Transfer execution will not exceed NDC
    sw -> sw: Reserve funds
    sw -> sw: Perform validation
    end
    alt Validation successful
    sw -> sw: Commit funds
    sw -> sob: PUT /transfers/{id} \n transferState=COMMITTED
    sob -> backend: Transfer successful \n HTTP 200 result (sync)
    else Validation fails
    sw -> sw: Cancel reserved funds
    sw -> sob: PUT /transfers/{id} \n transferState=ABORTED
    sob -> backend: Transfer failed (sync)
    end

@enduml